# Generated by Django 6.0.7 on 2026-07-23 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('ORGANIZER', 'Organizer'), ('ADMIN', 'Admin')], default='customer', max_length=20),
        ),
    ]
